name: pre-commit-checks

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - dev*
  pull_request:
  release:
    types:
      - published

jobs:
  check:
    name: Run checks with pre-commit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - uses: pre-commit/action@v3.0.0
        with:
          extra_args: --hook-stage manual --all-files
